version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/aelve/codesearch-engine
    steps:
      - checkout
      - run: go get github.com/aelve/codesearch-engine/cmd/...
      - run: go build -a -v ./cmd/...
      - run: go test ./...
